<?php

use Drupal\field\Entity\FieldStorageConfig;
use Drupal\field\Entity\FieldConfig;
use Drupal\views\ViewExecutable;
use Drupal\Core\Link;
use Drupal\Core\Url;




/**
 * Implementation of hook_form_BASE_FORM_ID_alter().
 */

// function attendance_form_views_exposed_form_alter(&$form, &$form_state, $form_id)
// {
//   // $form['new_button'] = [
//   //   '#type' => 'submit',
//   //   '#value' => t('New Button'),
//   //   '#attributes' => [
//   //     'class' => ['my-custom-button-class'], // Add custom CSS classes if needed.
//   //   ],
//   //   '#submit' => ['mymodule_new_button_submit'], // Optional: Specify a custom submit handler.
//   // ];
// }


/**
 * Implements hook_preprocess_views_view_table().
 */
function attendance_preprocess_views_view_table(&$variables)
{
  $view = $variables['view'];

  if ($view->id() === 'user_admin_people') {
    $variables["header"]["attendance"] = [
      "content" => "勤怠管理",
      "default_classes" => true
    ];

    foreach ($variables['rows'] as $index => &$row) {
      //dump($row);exit;
      $row["columns"]["attendance"]["content"][] = [
        'field_output' => [
          '#type' => 'link',
          '#title' => "確認",
          '#url' => Url::fromRoute('attendance.admin_list', ['user_id' => $variables['result'][$index]->uid]), // 必要に応じてカスタムURLを設定
          '#attributes' => [
            'class' => ['attendance-button'],
          ],
        ],
      ];
    }
  }
}
